#!/usr/bin/env bash

description "Extension for managing Rails (http://rubyonrails.org/)."

action "install" "Installs ${package_name} gem."
action "setup" "Bootstrap the current user's directory for a rails application deployment."
action "logtail" "Tail all logs in shared/log."
action "console" "Start an irb rails console."
action "dbconsole" "Start a database console."
action "migrate" "Run migrations."

show_help

