#!/bin/sh

typeset -ga scm_flags extension_args > /dev/null

typeset -gx log_path shared_path project_root repository_url environment project \
  database server ruby_string > /dev/null

typeset -g file

ruby_string="ruby-1.9.3"

