#!/usr/bin/env bash

description "Extension for managing Unicorn (http://unicorn.bogomips.org/)."

action "install" "Installs ${package_name} gem."
action "config {action}" "Where actions is one of {setup}"
action "service {action}" "Where action is in {start,stop,restart,reload,logs,increase,decrease,terminate,list,pause,unpause}."
action "help" "Display this help text."

show_help usage

