#!/bin/sh

passenger_initialize()
{
  fail "BDSM Extension '${extension}' has not been implemented yet."
}

passenger_install() {
  log "Passenger Applications are 'installed' by adding an Nginx/Apache configuration file."
}

passenger_start() {
  log "Passenger Applications are started by starting Nginx/Apache."
}

passenger_stop() {
  log "Passenger Applications are stopped by stopping Nginx/Apache."
}

passenger_restart() {
  log "Triggering restart of Passenger application."

  ensure_paths_exist "$release_path/tmp"

  ensure_files_exist "$release_path/tmp/restart.txt"

  log "Restart triggered."
}

