#!/bin/sh

usage()
{
  log "
CLI Arguments:

  -r|--repository  - The URL for the project repository code.

  -E|--environment - The environment (eg. production,staging,etc...)

  -p|--project     - The project name, defaults to current user name

  -D|--database)   - Database name

  -s|--server      - Application server (eg. unicorn, thin, etc...)

  --help           - This help text

  --licence        - Display extension license
"
}

number_of_args=${#extension_args[@]}

for ((index=0 ; index < $number_of_args ; index++))
do
  token="${extension_args[$index]}"

  case "$token" in
    -r|--repo|--repository)
      repository_url="${extension_args[$((++index))]}"
      ;;
    -E|--environment|--env)
      environment="${extension_args[$((++index))]}"
      ;;
    -p|--project)
      project="${extension_args[$((++index))]}"
      ;;
    -D|--database|--db)
      database="${extension_args[$((++index))]}"
      ;;
    -s|--server)
      server="${extension_args[$((++index))]}"
      ;;
    --scm-flag|-F)
      scm_flags+=("${extension_args[$((++index))]}")
      ;;
    --help)
      usage
      exit 0
      ;;
    --trace)
      set -o xtrace
      ;;
    --licence)
      display_extension_licence
      exit 0
      ;;
  esac
done

